### ISSUE TITLE
What is the relationship with phamthivan2996/commonstrings?

### ISSUE THREAD

**Issue by tripleee** [duongkstn/common_multiple_strings#1]
This project and https://github.com/phamthivan2996/commonstrings seem quite similar, and the same author has committed most of the code. What is the relationship between these two projects?

**Comment by duongkstn** [comment]
Hi @tripleee , this repos is up-to-date. You can run this code in C++ and Python

Otherwise, if you want to use as a Python library, it is recommended to `pip install commonstrings` (https://github.com/phamthivan2996/commonstrings)
